---
apiVersion: v1
kind: Service
metadata:
  name: go-app
  labels:
    app: go-app
spec:
  type: NodePort
  ports:
    - name: api
      port: 4444
      targetPort: 4444
      nodePort: 31111
  selector:
    app: go-app
